export const PLAYERS = [
  // ─── CSK (Chennai Super Kings) ───────────────────────────────────────────
  { id: 1,  name: "MS Dhoni",           role: "Wicketkeeper", team: "CSK", basePrice: 16, image: "🧤" },
  { id: 2,  name: "Ruturaj Gaikwad",    role: "Batsman",      team: "CSK", basePrice: 14, image: "🏏" },
  { id: 3,  name: "Ravindra Jadeja",    role: "All-Rounder",  team: "CSK", basePrice: 14, image: "⚡" },
  { id: 4,  name: "Deepak Chahar",      role: "Bowler",       team: "CSK", basePrice: 10, image: "🎯" },
  { id: 5,  name: "Moeen Ali",          role: "All-Rounder",  team: "CSK", basePrice: 9,  image: "⚡" },
  { id: 6,  name: "Devon Conway",       role: "Wicketkeeper", team: "CSK", basePrice: 10, image: "🧤" },
  { id: 7,  name: "Shivam Dube",        role: "All-Rounder",  team: "CSK", basePrice: 9,  image: "⚡" },
  { id: 8,  name: "Tushar Deshpande",   role: "Bowler",       team: "CSK", basePrice: 7,  image: "🎯" },
  { id: 9,  name: "Matheesha Pathirana",role: "Bowler",       team: "CSK", basePrice: 8,  image: "🎯" },
  { id: 10, name: "Rachin Ravindra",    role: "All-Rounder",  team: "CSK", basePrice: 9,  image: "⚡" },
  { id: 11, name: "Ajinkya Rahane",     role: "Batsman",      team: "CSK", basePrice: 7,  image: "🏏" },
  { id: 12, name: "Mitchell Santner",   role: "All-Rounder",  team: "CSK", basePrice: 8,  image: "⚡" },
  { id: 13, name: "Sameer Rizvi",       role: "Batsman",      team: "CSK", basePrice: 6,  image: "🏏" },
  { id: 14, name: "Mustafizur Rahman",  role: "Bowler",       team: "CSK", basePrice: 8,  image: "🎯" },
  { id: 15, name: "Prashant Solanki",   role: "Bowler",       team: "CSK", basePrice: 5,  image: "🎯" },
  { id: 16, name: "Daryl Mitchell",     role: "All-Rounder",  team: "CSK", basePrice: 8,  image: "⚡" },

  // ─── MI (Mumbai Indians) ─────────────────────────────────────────────────
  { id: 17, name: "Rohit Sharma",       role: "Batsman",      team: "MI",  basePrice: 18, image: "🏏" },
  { id: 18, name: "Jasprit Bumrah",     role: "Bowler",       team: "MI",  basePrice: 16, image: "🎯" },
  { id: 19, name: "Suryakumar Yadav",   role: "Batsman",      team: "MI",  basePrice: 14, image: "🏏" },
  { id: 20, name: "Hardik Pandya",      role: "All-Rounder",  team: "MI",  basePrice: 15, image: "⚡" },
  { id: 21, name: "Ishan Kishan",       role: "Wicketkeeper", team: "MI",  basePrice: 12, image: "🧤" },
  { id: 22, name: "Tilak Varma",        role: "Batsman",      team: "MI",  basePrice: 10, image: "🏏" },
  { id: 23, name: "Tim David",          role: "Batsman",      team: "MI",  basePrice: 9,  image: "🏏" },
  { id: 24, name: "Naman Dhir",         role: "All-Rounder",  team: "MI",  basePrice: 6,  image: "⚡" },
  { id: 25, name: "Piyush Chawla",      role: "Bowler",       team: "MI",  basePrice: 6,  image: "🎯" },
  { id: 26, name: "Gerald Coetzee",     role: "Bowler",       team: "MI",  basePrice: 8,  image: "🎯" },
  { id: 27, name: "Nuwan Thushara",     role: "Bowler",       team: "MI",  basePrice: 7,  image: "🎯" },
  { id: 28, name: "Romario Shepherd",   role: "All-Rounder",  team: "MI",  basePrice: 7,  image: "⚡" },
  { id: 29, name: "Shreyas Iyer",       role: "Batsman",      team: "MI",  basePrice: 13, image: "🏏" },
  { id: 30, name: "Dewald Brevis",      role: "Batsman",      team: "MI",  basePrice: 7,  image: "🏏" },
  { id: 31, name: "Mohammad Nabi",      role: "All-Rounder",  team: "MI",  basePrice: 7,  image: "⚡" },
  { id: 32, name: "Arjun Tendulkar",    role: "Bowler",       team: "MI",  basePrice: 4,  image: "🎯" },

  // ─── RCB (Royal Challengers Bengaluru) ───────────────────────────────────
  { id: 33, name: "Virat Kohli",        role: "Batsman",      team: "RCB", basePrice: 21, image: "🏏" },
  { id: 34, name: "Faf du Plessis",     role: "Batsman",      team: "RCB", basePrice: 10, image: "🏏" },
  { id: 35, name: "Glenn Maxwell",      role: "All-Rounder",  team: "RCB", basePrice: 12, image: "⚡" },
  { id: 36, name: "Mohammed Siraj",     role: "Bowler",       team: "RCB", basePrice: 11, image: "🎯" },
  { id: 37, name: "Dinesh Karthik",     role: "Wicketkeeper", team: "RCB", basePrice: 9,  image: "🧤" },
  { id: 38, name: "Rajat Patidar",      role: "Batsman",      team: "RCB", basePrice: 8,  image: "🏏" },
  { id: 39, name: "Cameron Green",      role: "All-Rounder",  team: "RCB", basePrice: 11, image: "⚡" },
  { id: 40, name: "Yash Dayal",         role: "Bowler",       team: "RCB", basePrice: 7,  image: "🎯" },
  { id: 41, name: "Alzarri Joseph",     role: "Bowler",       team: "RCB", basePrice: 8,  image: "🎯" },
  { id: 42, name: "Swapnil Singh",      role: "All-Rounder",  team: "RCB", basePrice: 5,  image: "⚡" },
  { id: 43, name: "Anuj Rawat",         role: "Wicketkeeper", team: "RCB", basePrice: 5,  image: "🧤" },
  { id: 44, name: "Mahipal Lomror",     role: "All-Rounder",  team: "RCB", basePrice: 5,  image: "⚡" },
  { id: 45, name: "Lockie Ferguson",    role: "Bowler",       team: "RCB", basePrice: 8,  image: "🎯" },
  { id: 46, name: "Tom Curran",         role: "All-Rounder",  team: "RCB", basePrice: 7,  image: "⚡" },
  { id: 47, name: "Akash Deep",         role: "Bowler",       team: "RCB", basePrice: 6,  image: "🎯" },
  { id: 48, name: "Will Jacks",         role: "All-Rounder",  team: "RCB", basePrice: 9,  image: "⚡" },

  // ─── KKR (Kolkata Knight Riders) ─────────────────────────────────────────
  { id: 49, name: "Andre Russell",      role: "All-Rounder",  team: "KKR", basePrice: 13, image: "⚡" },
  { id: 50, name: "Sunil Narine",       role: "All-Rounder",  team: "KKR", basePrice: 12, image: "⚡" },
  { id: 51, name: "Pat Cummins",        role: "Bowler",       team: "KKR", basePrice: 14, image: "🎯" },
  { id: 52, name: "Nitish Rana",        role: "Batsman",      team: "KKR", basePrice: 9,  image: "🏏" },
  { id: 53, name: "Venkatesh Iyer",     role: "All-Rounder",  team: "KKR", basePrice: 10, image: "⚡" },
  { id: 54, name: "Rinku Singh",        role: "Batsman",      team: "KKR", basePrice: 11, image: "🏏" },
  { id: 55, name: "Phil Salt",          role: "Wicketkeeper", team: "KKR", basePrice: 10, image: "🧤" },
  { id: 56, name: "Harshit Rana",       role: "Bowler",       team: "KKR", basePrice: 7,  image: "🎯" },
  { id: 57, name: "Varun Chakravarthy", role: "Bowler",       team: "KKR", basePrice: 9,  image: "🎯" },
  { id: 58, name: "Angkrish Raghuvanshi",role:"Batsman",      team: "KKR", basePrice: 5,  image: "🏏" },
  { id: 59, name: "Manish Pandey",      role: "Batsman",      team: "KKR", basePrice: 6,  image: "🏏" },
  { id: 60, name: "Rahmanullah Gurbaz", role: "Wicketkeeper", team: "KKR", basePrice: 8,  image: "🧤" },
  { id: 61, name: "Mitchell Starc",     role: "Bowler",       team: "KKR", basePrice: 13, image: "🎯" },
  { id: 62, name: "Jason Roy",          role: "Batsman",      team: "KKR", basePrice: 8,  image: "🏏" },
  { id: 63, name: "Suyash Sharma",      role: "Bowler",       team: "KKR", basePrice: 5,  image: "🎯" },
  { id: 64, name: "Ramandeep Singh",    role: "All-Rounder",  team: "KKR", basePrice: 5,  image: "⚡" },

  // ─── DC (Delhi Capitals) ─────────────────────────────────────────────────
  { id: 65, name: "Rishabh Pant",       role: "Wicketkeeper", team: "DC",  basePrice: 16, image: "🧤" },
  { id: 66, name: "David Warner",       role: "Batsman",      team: "DC",  basePrice: 10, image: "🏏" },
  { id: 67, name: "Axar Patel",         role: "All-Rounder",  team: "DC",  basePrice: 11, image: "⚡" },
  { id: 68, name: "Anrich Nortje",      role: "Bowler",       team: "DC",  basePrice: 10, image: "🎯" },
  { id: 69, name: "Mitchell Marsh",     role: "All-Rounder",  team: "DC",  basePrice: 11, image: "⚡" },
  { id: 70, name: "Prithvi Shaw",       role: "Batsman",      team: "DC",  basePrice: 8,  image: "🏏" },
  { id: 71, name: "Kuldeep Yadav",      role: "Bowler",       team: "DC",  basePrice: 10, image: "🎯" },
  { id: 72, name: "Rovman Powell",      role: "Batsman",      team: "DC",  basePrice: 8,  image: "🏏" },
  { id: 73, name: "Mukesh Kumar",       role: "Bowler",       team: "DC",  basePrice: 6,  image: "🎯" },
  { id: 74, name: "Tristan Stubbs",     role: "Wicketkeeper", team: "DC",  basePrice: 7,  image: "🧤" },
  { id: 75, name: "Yash Dhull",         role: "Batsman",      team: "DC",  basePrice: 5,  image: "🏏" },
  { id: 76, name: "Sumit Kumar",        role: "Bowler",       team: "DC",  basePrice: 4,  image: "🎯" },
  { id: 77, name: "Ishant Sharma",      role: "Bowler",       team: "DC",  basePrice: 7,  image: "🎯" },
  { id: 78, name: "Khaleel Ahmed",      role: "Bowler",       team: "DC",  basePrice: 7,  image: "🎯" },
  { id: 79, name: "Rilee Rossouw",      role: "Batsman",      team: "DC",  basePrice: 8,  image: "🏏" },
  { id: 80, name: "Jake Fraser-McGurk", role: "Batsman",      team: "DC",  basePrice: 8,  image: "🏏" },

  // ─── RR (Rajasthan Royals) ────────────────────────────────────────────────
  { id: 81, name: "Sanju Samson",       role: "Wicketkeeper", team: "RR",  basePrice: 14, image: "🧤" },
  { id: 82, name: "Jos Buttler",        role: "Wicketkeeper", team: "RR",  basePrice: 15, image: "🧤" },
  { id: 83, name: "Yuzvendra Chahal",   role: "Bowler",       team: "RR",  basePrice: 10, image: "🎯" },
  { id: 84, name: "Trent Boult",        role: "Bowler",       team: "RR",  basePrice: 10, image: "🎯" },
  { id: 85, name: "Shimron Hetmyer",    role: "Batsman",      team: "RR",  basePrice: 9,  image: "🏏" },
  { id: 86, name: "Yashasvi Jaiswal",   role: "Batsman",      team: "RR",  basePrice: 13, image: "🏏" },
  { id: 87, name: "Devdutt Padikkal",   role: "Batsman",      team: "RR",  basePrice: 8,  image: "🏏" },
  { id: 88, name: "Riyan Parag",        role: "All-Rounder",  team: "RR",  basePrice: 9,  image: "⚡" },
  { id: 89, name: "Ravichandran Ashwin",role: "All-Rounder",  team: "RR",  basePrice: 10, image: "⚡" },
  { id: 90, name: "Sandeep Sharma",     role: "Bowler",       team: "RR",  basePrice: 6,  image: "🎯" },
  { id: 91, name: "Adam Zampa",         role: "Bowler",       team: "RR",  basePrice: 8,  image: "🎯" },
  { id: 92, name: "Dhruv Jurel",        role: "Wicketkeeper", team: "RR",  basePrice: 7,  image: "🧤" },
  { id: 93, name: "Rovman Powell",      role: "Batsman",      team: "RR",  basePrice: 7,  image: "🏏" },
  { id: 94, name: "Nandre Burger",      role: "Bowler",       team: "RR",  basePrice: 6,  image: "🎯" },
  { id: 95, name: "Kuldeep Sen",        role: "Bowler",       team: "RR",  basePrice: 5,  image: "🎯" },
  { id: 96, name: "Shubham Dubey",      role: "All-Rounder",  team: "RR",  basePrice: 5,  image: "⚡" },

  // ─── GT (Gujarat Titans) ─────────────────────────────────────────────────
  { id: 97,  name: "Hardik Pandya",     role: "All-Rounder",  team: "GT",  basePrice: 15, image: "⚡" },
  { id: 98,  name: "Shubman Gill",      role: "Batsman",      team: "GT",  basePrice: 13, image: "🏏" },
  { id: 99,  name: "Rashid Khan",       role: "Bowler",       team: "GT",  basePrice: 14, image: "🎯" },
  { id: 100, name: "Mohammed Shami",    role: "Bowler",       team: "GT",  basePrice: 12, image: "🎯" },
  { id: 101, name: "Wriddhiman Saha",   role: "Wicketkeeper", team: "GT",  basePrice: 7,  image: "🧤" },
  { id: 102, name: "David Miller",      role: "Batsman",      team: "GT",  basePrice: 11, image: "🏏" },
  { id: 103, name: "Abhinav Manohar",   role: "Batsman",      team: "GT",  basePrice: 7,  image: "🏏" },
  { id: 104, name: "Rahul Tewatia",     role: "All-Rounder",  team: "GT",  basePrice: 8,  image: "⚡" },
  { id: 105, name: "Noor Ahmad",        role: "Bowler",       team: "GT",  basePrice: 8,  image: "🎯" },
  { id: 106, name: "Sai Sudharsan",     role: "Batsman",      team: "GT",  basePrice: 9,  image: "🏏" },
  { id: 107, name: "Mohit Sharma",      role: "Bowler",       team: "GT",  basePrice: 7,  image: "🎯" },
  { id: 108, name: "Darshan Nalkande",  role: "Bowler",       team: "GT",  basePrice: 5,  image: "🎯" },
  { id: 109, name: "Vijay Shankar",     role: "All-Rounder",  team: "GT",  basePrice: 6,  image: "⚡" },
  { id: 110, name: "B Sai Sudharsan",   role: "Batsman",      team: "GT",  basePrice: 8,  image: "🏏" },
  { id: 111, name: "Azmatullah Omarzai",role: "All-Rounder",  team: "GT",  basePrice: 7,  image: "⚡" },
  { id: 112, name: "Kane Williamson",   role: "Batsman",      team: "GT",  basePrice: 10, image: "🏏" },

  // ─── LSG (Lucknow Super Giants) ──────────────────────────────────────────
  { id: 113, name: "KL Rahul",          role: "Wicketkeeper", team: "LSG", basePrice: 15, image: "🧤" },
  { id: 114, name: "Quinton de Kock",   role: "Wicketkeeper", team: "LSG", basePrice: 12, image: "🧤" },
  { id: 115, name: "Nicholas Pooran",   role: "Wicketkeeper", team: "LSG", basePrice: 11, image: "🧤" },
  { id: 116, name: "Marcus Stoinis",    role: "All-Rounder",  team: "LSG", basePrice: 10, image: "⚡" },
  { id: 117, name: "Ravi Bishnoi",      role: "Bowler",       team: "LSG", basePrice: 10, image: "🎯" },
  { id: 118, name: "Mark Wood",         role: "Bowler",       team: "LSG", basePrice: 11, image: "🎯" },
  { id: 119, name: "Krunal Pandya",     role: "All-Rounder",  team: "LSG", basePrice: 9,  image: "⚡" },
  { id: 120, name: "Deepak Hooda",      role: "All-Rounder",  team: "LSG", basePrice: 7,  image: "⚡" },
  { id: 121, name: "Ayush Badoni",      role: "Batsman",      team: "LSG", basePrice: 7,  image: "🏏" },
  { id: 122, name: "Manan Vohra",       role: "Batsman",      team: "LSG", basePrice: 5,  image: "🏏" },
  { id: 123, name: "Kyle Mayers",       role: "All-Rounder",  team: "LSG", basePrice: 8,  image: "⚡" },
  { id: 124, name: "Naveen-ul-Haq",     role: "Bowler",       team: "LSG", basePrice: 8,  image: "🎯" },
  { id: 125, name: "Amit Mishra",       role: "Bowler",       team: "LSG", basePrice: 5,  image: "🎯" },
  { id: 126, name: "Prerak Mankad",     role: "All-Rounder",  team: "LSG", basePrice: 5,  image: "⚡" },
  { id: 127, name: "Shamar Joseph",     role: "Bowler",       team: "LSG", basePrice: 7,  image: "🎯" },
  { id: 128, name: "Mayank Yadav",      role: "Bowler",       team: "LSG", basePrice: 9,  image: "🎯" },

  // ─── PBKS (Punjab Kings) ─────────────────────────────────────────────────
  { id: 129, name: "Shikhar Dhawan",    role: "Batsman",      team: "PBKS", basePrice: 9, image: "🏏" },
  { id: 130, name: "Sam Curran",        role: "All-Rounder",  team: "PBKS", basePrice: 12, image: "⚡" },
  { id: 131, name: "Arshdeep Singh",    role: "Bowler",       team: "PBKS", basePrice: 11, image: "🎯" },
  { id: 132, name: "Jonny Bairstow",    role: "Wicketkeeper", team: "PBKS", basePrice: 10, image: "🧤" },
  { id: 133, name: "Liam Livingstone",  role: "All-Rounder",  team: "PBKS", basePrice: 11, image: "⚡" },
  { id: 134, name: "Kagiso Rabada",     role: "Bowler",       team: "PBKS", basePrice: 11, image: "🎯" },
  { id: 135, name: "Rishi Dhawan",      role: "All-Rounder",  team: "PBKS", basePrice: 5,  image: "⚡" },
  { id: 136, name: "Harpreet Brar",     role: "All-Rounder",  team: "PBKS", basePrice: 6,  image: "⚡" },
  { id: 137, name: "Harshal Patel",     role: "Bowler",       team: "PBKS", basePrice: 9,  image: "🎯" },
  { id: 138, name: "Atharva Taide",     role: "Batsman",      team: "PBKS", basePrice: 5,  image: "🏏" },
  { id: 139, name: "Sikandar Raza",     role: "All-Rounder",  team: "PBKS", basePrice: 7,  image: "⚡" },
  { id: 140, name: "Vidwath Kaverappa", role: "Bowler",       team: "PBKS", basePrice: 5,  image: "🎯" },
  { id: 141, name: "Prabhsimran Singh", role: "Wicketkeeper", team: "PBKS", basePrice: 7,  image: "🧤" },
  { id: 142, name: "Chris Woakes",      role: "All-Rounder",  team: "PBKS", basePrice: 9,  image: "⚡" },
  { id: 143, name: "Rilee Rossouw",     role: "Batsman",      team: "PBKS", basePrice: 7,  image: "🏏" },
  { id: 144, name: "Nathan Ellis",      role: "Bowler",       team: "PBKS", basePrice: 7,  image: "🎯" },

  // ─── EXTRA / UNCAPPED STARS (15 players) ─────────────────────────────────
  { id: 145, name: "Heinrich Klaasen",  role: "Wicketkeeper", team: "INT", basePrice: 11, image: "🧤" },
  { id: 146, name: "Kieron Pollard",    role: "All-Rounder",  team: "INT", basePrice: 9,  image: "⚡" },
  { id: 147, name: "Dawid Malan",       role: "Batsman",      team: "INT", basePrice: 8,  image: "🏏" },
  { id: 148, name: "Wanindu Hasaranga", role: "All-Rounder",  team: "INT", basePrice: 10, image: "⚡" },
  { id: 149, name: "Ben Stokes",        role: "All-Rounder",  team: "INT", basePrice: 13, image: "⚡" },
  { id: 150, name: "Babar Azam",        role: "Batsman",      team: "INT", basePrice: 12, image: "🏏" },
  { id: 151, name: "Shaheen Afridi",    role: "Bowler",       team: "INT", basePrice: 11, image: "🎯" },
  { id: 152, name: "Rassie van der Dussen", role: "Batsman",  team: "INT", basePrice: 9,  image: "🏏" },
  { id: 153, name: "Quinton de Kock",   role: "Wicketkeeper", team: "INT", basePrice: 11, image: "🧤" },
  { id: 154, name: "Fakhar Zaman",      role: "Batsman",      team: "INT", basePrice: 8,  image: "🏏" },
  { id: 155, name: "Tabraiz Shamsi",    role: "Bowler",       team: "INT", basePrice: 7,  image: "🎯" },
  { id: 156, name: "Brandon McMahon",   role: "All-Rounder",  team: "INT", basePrice: 6,  image: "⚡" },
  { id: 157, name: "Mohammad Rizwan",   role: "Wicketkeeper", team: "INT", basePrice: 10, image: "🧤" },
  { id: 158, name: "Finn Allen",        role: "Batsman",      team: "INT", basePrice: 7,  image: "🏏" },
  { id: 159, name: "Reece Topley",      role: "Bowler",       team: "INT", basePrice: 7,  image: "🎯" },
];